#!/usr/bin/env node
// Full renderer evidence through ordinary EVM deployment; Node supplies original resources only.
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {createHash} from 'node:crypto';
import {spawn,execFileSync} from 'node:child_process';
import {connect} from 'node:net';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {canonical} from '../wad/wad.ts';
import {validateSchema} from '../wad/schema.ts';
import {instrumentGasMarkers,sha,traceMemory} from '../reference/phase2_data/instrument.mjs';
import {FrameSubscription,decodeFrame,stepData} from '../../web/protocol.mjs';
import {validatePalette} from '../../web/palette.mjs';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');process.chdir(root);
const argv=process.argv.slice(2),option=(name,fallback)=>{const i=argv.indexOf(name);return i<0?fallback:argv[i+1];};
const prefix=option('--output-prefix','artifacts/local/renderer'),port=Number(option('--port','18567')),keepAlive=argv.includes('--keep-alive');
assert(Number.isInteger(port)&&port>1024&&port<65536);
await mkdir(dirname(prefix),{recursive:true});await writeFile(prefix+'.json',JSON.stringify({kind:'doom-world-view-ordinary-e2e',pass:false,status:'running'})+'\n');
const rpcUrl=`http://127.0.0.1:${port}`,wsUrl=rpcUrl.replace('http','ws'),gas='0x3b9aca00';
const bundle=JSON.parse(await readFile('artifacts/local/wad/bundle.json','utf8'));
validateSchema(bundle,JSON.parse(await readFile('schemas/resource-bundle-v0.schema.json','utf8')));
const pinned=JSON.parse(await readFile('test/fixtures/wad/snapshot.json','utf8'));assert.deepEqual(bundle.resourceIdentity,pinned.resourceIdentity);
assert.equal(sha(canonical(Object.fromEntries(Object.entries(bundle).filter(([k])=>!['resourceIdentity','blobFile'].includes(k))))),bundle.resourceIdentity.bundleSha256);
const blob=await readFile('artifacts/local/wad/resources.bin');assert.equal(blob.length,bundle.blobByteLength);assert.equal(sha(blob),bundle.blobSha256);
const directory=Buffer.alloc(bundle.lumps.length*16);let cursor=0;
for(const[i,l]of bundle.lumps.entries()){assert.equal(l.id,i);assert.equal(l.offset,cursor);cursor+=l.length;assert(cursor<=blob.length);Buffer.from(l.nameHex,'hex').copy(directory,i*16);directory.writeUInt32LE(l.offset,i*16+8);directory.writeUInt32LE(l.length,i*16+12);}
assert.equal(cursor,blob.length);assert.deepEqual(directory,await readFile('test/fixtures/phase2_data/directory.bin'));
const native=JSON.parse(await readFile('test/fixtures/renderer/manifest.json','utf8'));assert.deepEqual(native.resourceIdentity,bundle.resourceIdentity);
for(const[name,digest]of Object.entries(native.files))assert.equal(sha(await readFile('test/fixtures/renderer/'+name)),digest,'stale native '+name);
const palettePath='test/fixtures/wad/palette.json',palette=JSON.parse(await readFile(palettePath,'utf8'));await validatePalette(palette,bundle.resourceIdentity,'wad');
execFileSync(process.execPath,['tools/wad/check-source-identity.mjs'],{stdio:'inherit',timeout:30000});
console.log('Compiling production Doom and separate RendererProbe (up to 300 seconds).');
execFileSync(resolve('.toolchain/bin/forge'),['build','src/support/RendererProbe.sol','src/evm/Doom.sol','src/evm/ResourceStore.sol'],{stdio:'pipe',timeout:300000,maxBuffer:8*1024*1024});
const artifact=JSON.parse(await readFile('out/RendererProbe.sol/RendererProbe.json','utf8'));
const doom=JSON.parse(await readFile('out/Doom.sol/Doom.json','utf8'));
const chunk=JSON.parse(await readFile('out/ResourceStore.sol/ResourceStore.json','utf8'));
const telemetry=instrumentGasMarkers(artifact,await readFile('src/support/RendererProbe.sol','utf8'));
const word=x=>BigInt(x).toString(16).padStart(64,'0'),tail=b=>word(b.length)+b.toString('hex').padEnd(Math.ceil(b.length/32)*64,'0');
const encode=(addresses,dir)=>{const a=word(addresses.length)+addresses.map(x=>x.slice(2).padStart(64,'0')).join('');return word(64)+word(64+a.length/2)+a+tail(dir);};
async function fileSha(path){const hash=createHash('sha256');for await(const bytes of createReadStream(path))hash.update(bytes);return hash.digest('hex');}
const toolchainHashes=Object.fromEntries(await Promise.all([['anvil',resolve('.toolchain/bin/anvil')],['solc',resolve('.toolchain/bin/solc')],['forge',resolve('.toolchain/bin/forge')],['node',process.execPath]].map(async([name,path])=>[name,await fileSha(path)])));
let rpcId=0;
async function rpc(method,params=[]){const response=await fetch(rpcUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:++rpcId,method,params}),signal:AbortSignal.timeout(120000)});assert(response.ok);const value=await response.json();if(value.error)throw Object.assign(Error(`${method}: ${JSON.stringify(value.error)}`),{rpcError:value.error});return value.result;}
const sleep=ms=>new Promise(done=>setTimeout(done,ms));
async function waitFor(test,label,ms=30000){const end=performance.now()+ms;while(performance.now()<end){const result=await test();if(result)return result;await sleep(25);}throw Error('Timeout: '+label);}
async function receipt(hash){return waitFor(()=>rpc('eth_getTransactionReceipt',[hash]),'receipt '+hash,120000);}
async function stop(child){if(!child?.pid||child.exitCode!==null||child.signalCode!==null)return;await new Promise(done=>{let timer;const finish=()=>{clearTimeout(timer);child.removeListener('exit',finish);done();};child.once('exit',finish);child.kill('SIGTERM');timer=setTimeout(()=>{child.kill('SIGKILL');timer=setTimeout(finish,1500);},1500);});assert(child.exitCode!==null||child.signalCode!==null,'owned Anvil did not terminate');}
async function assertUnusedPort(){await new Promise((done,fail)=>{const socket=connect({host:'127.0.0.1',port});socket.once('connect',()=>{socket.destroy();fail(Error('Refusing occupied port'));});socket.once('error',error=>error.code==='ECONNREFUSED'?done():fail(error));socket.setTimeout(1000,()=>{socket.destroy();fail(Error('Port check timed out'));});});}
const nodeArgs=['--host','127.0.0.1','--port',String(port),'--hardfork','cancun','--disable-code-size-limit','--disable-block-gas-limit','--memory-limit','1073741824','--silent'];
let server,subscription,sampler,serverError='',spawnError,peakAnvilRssBytes=0,peakNodeRssBytes=process.memoryUsage().rss;
function sample(){peakNodeRssBytes=Math.max(peakNodeRssBytes,process.memoryUsage().rss);if(server?.pid)try{peakAnvilRssBytes=Math.max(peakAnvilRssBytes,Number(execFileSync('ps',['-o','rss=','-p',String(server.pid)],{encoding:'utf8'}).trim())*1024);}catch{}}
const signature=(a,name)=>'0x'+a.methodIdentifiers[name];
try {
  await assertUnusedPort();server=spawn(resolve('.toolchain/bin/anvil'),nodeArgs,{stdio:['ignore','ignore','pipe']});server.on('error',error=>spawnError=error);server.stderr.on('data',data=>serverError+=data);
  await waitFor(async()=>{if(spawnError)throw spawnError;assert.equal(server.exitCode,null,serverError);try{return await rpc('web3_clientVersion');}catch{return false;}},'Anvil startup');
  await rpc('anvil_setBlockGasLimit',[gas]);await rpc('evm_mine');const[from,other]=await rpc('eth_accounts');sampler=setInterval(sample,1000);sample();
  const transact=async(data,to,sender=from)=>{const start=performance.now(),hash=await rpc('eth_sendTransaction',[{from:sender,...(to?{to}:{}),data,gas}]),submitted=performance.now(),r=await receipt(hash);return{receipt:r,submitResponseMs:submitted-start,sendToReceiptMs:performance.now()-start,start};};
  const deploy=async(data)=>{const result=await transact(data);assert.equal(result.receipt.status,'0x1','ordinary CREATE failed');return result;};
  const deploySummary=x=>({address:x.receipt.contractAddress,transactionHash:x.receipt.transactionHash,gas:Number(BigInt(x.receipt.gasUsed)),sendToReceiptMs:x.sendToReceiptMs});
  const chunks=[],uploadStart=performance.now();
  for(let off=0;off<blob.length;off+=16384){const payload=blob.subarray(off,off+16384),r=await deploy(chunk.bytecode.object+word(32)+tail(payload)),runtime='0x00'+payload.toString('hex');assert.equal(await rpc('eth_getCode',[r.receipt.contractAddress,'latest']),runtime);chunks.push({index:chunks.length,offset:off,...deploySummary(r),runtimeBytes:payload.length+1,runtimeSha256:sha(Buffer.from(runtime.slice(2),'hex'))});if(chunks.length%250===0)console.log(`Uploaded and exact-verified ${chunks.length}/1755 chunks`);}
  assert.equal(chunks.length,1755);const uploadMs=performance.now()-uploadStart,encoded=encode(chunks.map(c=>c.address),directory);
  const production=await deploy(doom.bytecode.object+encoded),normal=await deploy(artifact.bytecode.object+encoded),measured=await deploy('0x'+telemetry.creation.toString('hex')+encoded);
  const address=production.receipt.contractAddress,normalAddress=normal.receipt.contractAddress,measuredAddress=measured.receipt.contractAddress;
  assert.equal(normal.receipt.gasUsed,measured.receipt.gasUsed,'probe constructor gas differs');
  assert.equal(await rpc('eth_getCode',[normalAddress,'latest']),artifact.deployedBytecode.object);assert.equal(await rpc('eth_getCode',[measuredAddress,'latest']),'0x'+telemetry.runtime.toString('hex'));
  const productionRuntime=Buffer.from(doom.deployedBytecode.object.slice(2),'hex'),immutableReferences=doom.deployedBytecode.immutableReferences;assert.equal(Object.keys(immutableReferences).length,1,'unexpected production immutables');
  for(const locations of Object.values(immutableReferences))for(const{start,length}of locations){assert.equal(length,32);assert(productionRuntime.subarray(start,start+length).every(v=>v===0),'nonzero immutable placeholder');Buffer.from(from.slice(2).padStart(64,'0'),'hex').copy(productionRuntime,start);}
  assert.equal(await rpc('eth_getCode',[address,'latest']),'0x'+productionRuntime.toString('hex'));
  const call=(to,data,sender=from)=>rpc('eth_call',[{from:sender,to,data,gas},'latest']);
  assert.equal(await call(address,signature(doom,'driver()')),'0x'+from.slice(2).padStart(64,'0'));
  const identity=bundle.resourceIdentity,identityWords=word(identity.schemaVersion)+identity.wadSha256+identity.bundleSha256+identity.paletteSha256+word(identity.paletteVariant);
  for(const[a,artifact_]of[[address,doom],[normalAddress,artifact],[measuredAddress,artifact]])assert.equal(await call(a,signature(artifact_,'resourceIdentity()')),'0x'+identityWords);
  const compiler={solc:execFileSync(resolve('.toolchain/bin/solc'),['--version'],{encoding:'utf8'}).trim(),forge:execFileSync(resolve('.toolchain/bin/forge'),['--version'],{encoding:'utf8'}).trim(),node:process.version,settings:doom.metadata.settings};
  const sourcePaths=[...new Set([...Object.keys(doom.metadata.sources),...Object.keys(artifact.metadata.sources),'src/evm/ResourceStore.sol','tools/renderer/verify.mjs','tools/renderer/record.py','tools/renderer/browser-timing.js','tools/reference/phase2_data/instrument.mjs','tools/transport/browser-check.mjs','tools/transport/serve.mjs','web/app.mjs','web/protocol.mjs','web/palette.mjs','web/index.html','tools/tables/generate.py','tools/wad/check-source-identity.mjs','tools/wad/wad.ts','tools/wad/schema.ts','tools/reference/pixel_diff.py','scripts/check-schemas.py','schemas/resource-bundle-v0.schema.json','schemas/reference-v0.schema.json','tools/reference/info/generate.py','test/fixtures/renderer/manifest.json','test/fixtures/wad/palette.json','foundry.toml'])].sort();
  const sources=Object.fromEntries(await Promise.all(sourcePaths.map(async p=>[p,sha(await readFile(p))]))),rendererCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
  const build={compiler:'solc',version:compiler.solc,target:'Cancun ordinary EVM',flags:['optimizer-runs=200','via-ir=true','evm-version=cancun'],patchSha256:sha(canonical(sources)),harnessSha256:sources['tools/renderer/verify.mjs'],integerSemantics:'Explicit original int32/uint32 narrowing and pinned wrapping extensions; original undefined domains documented per module.',doubleSemantics:'No EVM floating point: FixedDiv2 integer arithmetic reproduces the pinned original binary64 accepted domain.'};
  await writeFile(prefix+'.build.json',JSON.stringify(build,null,2)+'\n');
  const parseProbe=hex=>{const bytes=Buffer.from(hex.slice(2),'hex'),w=i=>BigInt('0x'+bytes.subarray(i*32,(i+1)*32).toString('hex'));assert.equal(w(0),544n);assert.equal(w(17),64000n);assert.equal(bytes.length,544+32+64000);return{gas:[1,2,3].map(i=>Number(w(i))),memory:[4,5,6,7].map(i=>Number(w(i))),camera:[8,9,10,11].map(i=>Number(BigInt.asIntN(256,w(i)))),counts:[12,13,14,15,16].map(i=>Number(w(i))),pixels:bytes.subarray(576)};};
  const scenes=[];
  for(let i=0;i<8;i++) {
    const name=`full-angle${i}`,expected=native.cases.find(c=>c.name===name);assert(expected&&expected.mode==='full');assert.equal(expected.angle,i*0x20000000);
    const data=signature(artifact,'probe(uint32)')+word(expected.angle);let start=performance.now();const a=parseProbe(await call(normalAddress,data)),callMs=performance.now()-start;start=performance.now();const b=parseProbe(await call(measuredAddress,data)),measuredCallMs=performance.now()-start;
    assert.deepEqual(a.pixels,b.pixels);assert.deepEqual(a.gas,b.gas);assert.deepEqual(a.camera,b.camera);assert.deepEqual(a.counts,b.counts);assert.equal(sha(a.pixels),expected.frameSha256);
    assert.deepEqual(a.camera,[expected.scene.x,expected.scene.y,expected.scene.z,expected.angle]);assert.deepEqual(a.counts,['spawnedThings','drawsegs','visplanes','vissprites','subsectors'].map(k=>expected.scene[k]));for(const n of b.memory)assert(n>0&&n%32===0);
    const tx=await transact(data,normalAddress),mtx=await transact(data,measuredAddress);assert.equal(tx.receipt.status,'0x1');assert.equal(mtx.receipt.status,'0x1');assert.equal(tx.receipt.logs.length,0);assert.equal(mtx.receipt.logs.length,0);assert.equal(tx.receipt.gasUsed,mtx.receipt.gasUsed);
    const dir=prefix+'.frames/'+name;await mkdir(dir,{recursive:true});await writeFile(dir+'/pixels.bin',a.pixels);
    const camera={x:a.camera[0],y:a.camera[1],z:a.camera[2],angle:a.camera[3]};execFileSync('python3',['tools/renderer/record.py','--native','test/fixtures/renderer/'+name,'--actual',dir,'--build',prefix+'.build.json','--camera',JSON.stringify(camera)],{timeout:30000});
    const evidence={name,mode:'full',resourceIdentity:identity,camera,counts:a.counts,gametic:0,paletteVariant:0,resolution:[320,200],frameSha256:sha(a.pixels),pixelDiffCount:0,gasUsed:Number(BigInt(tx.receipt.gasUsed)),operationGas:a.gas,actualMemoryBytes:b.memory,ethCallMs:callMs,instrumentedEthCallMs:measuredCallMs,sendToReceiptMs:tx.sendToReceiptMs,transactionHash:tx.receipt.transactionHash,instrumentedTransactionHash:mtx.receipt.transactionHash,artifacts:dir};scenes.push(evidence);console.log(`${name}: exact, gas ${evidence.gasUsed}, MSIZE ${b.memory.at(-1)}, eth_call ${callMs.toFixed(1)}ms`);
  }
  const notifications=new Map();subscription=new FrameSubscription(wsUrl,address,log=>notifications.set(log.transactionHash,{log,at:performance.now()}));await subscription.connect();
  const productionFrames=[];await mkdir(prefix+'.receipts',{recursive:true});
  for(const[sequence,data]of[[1,stepData(1)],[2,signature(doom,'renderFrame()')]]) {
    const start=performance.now();await call(address,data);const callMs=performance.now()-start;
    const tx=await transact(data,address),r=tx.receipt;assert.equal(r.status,'0x1');assert.equal(r.logs.length,1);assert.equal(r.logs[0].address,address);
    const frame=decodeFrame(r.logs[0]);assert.equal(frame.frameId,BigInt(sequence));assert.equal(frame.inputSeq,sequence);assert.equal(frame.width,320);assert.equal(frame.height,200);assert.equal(sha(frame.pixels),scenes[0].frameSha256);
    const message=await waitFor(()=>notifications.get(r.transactionHash),'production Frame notification');assert.equal(message.log.data,r.logs[0].data);assert.deepEqual(message.log.topics,r.logs[0].topics);
    const receiptFile=prefix+'.receipts/frame'+sequence+'.json';await writeFile(receiptFile,JSON.stringify(r,null,2)+'\n');
    productionFrames.push({sequence,status:r.status,frameId:String(frame.frameId),inputSeq:frame.inputSeq,receiptFile,method:sequence===1?'stepAndRender':'renderFrame',transactionHash:r.transactionHash,gasUsed:Number(BigInt(r.gasUsed)),ethCallMs:callMs,sendToReceiptMs:tx.sendToReceiptMs,eventDeliveryMs:message.at-tx.start,oneFrame:true,frameSha256:sha(frame.pixels),pixelBytes:64000,abiDataBytes:(r.logs[0].data.length-2)/2,websocketReceiptPixelsEqual:true});
  }
  const counters=async()=>({frameId:Number(BigInt(await call(address,signature(doom,'frameId()')))),inputSeq:Number(BigInt(await call(address,signature(doom,'inputSeq()'))))});assert.deepEqual(await counters(),{frameId:2,inputSeq:2});
  const rejections=[];
  for(const[name,data,sender,error]of[['wrong-driver',stepData(3),other,'NotDriver()'],['buttons',signature(doom,'stepAndRender(uint32,uint32)')+word(1)+word(3),from,'UnsupportedButtons()'],['sequence-replay',stepData(2),from,'BadSequence()'],['sequence-skip',stepData(4),from,'BadSequence()']]) {
    const selector=execFileSync(resolve('.toolchain/bin/cast'),['sig',error],{encoding:'utf8'}).trim();let rejected;try{await call(address,data,sender);}catch(e){rejected=e;}assert.equal(rejected?.rpcError?.data,selector);
    const tx=await transact(data,address,sender);assert.equal(tx.receipt.status,'0x0');assert.equal(tx.receipt.logs.length,0);assert.deepEqual(await counters(),{frameId:2,inputSeq:2});await writeFile(prefix+'.receipts/'+name+'.json',JSON.stringify(tx.receipt,null,2)+'\n');rejections.push({name,status:tx.receipt.status,receiptFile:prefix+'.receipts/'+name+'.json',error,selector,transactionHash:tx.receipt.transactionHash,gasUsed:Number(BigInt(tx.receipt.gasUsed)),logs:0,countersUnchanged:true});
  }
  const wall=await transact(signature(artifact,'wallFrame()'),normalAddress);assert.equal(wall.receipt.status,'0x1');assert.equal(wall.receipt.logs.length,1);const wallPixels=decodeFrame(wall.receipt.logs[0]).pixels,wallExpected=native.cases.find(c=>c.name==='walls-angle0');assert.equal(wallExpected.mode,'walls');assert.equal(sha(wallPixels),wallExpected.frameSha256);
  const wallDir=prefix+'.frames/walls-angle0';await mkdir(wallDir,{recursive:true});await writeFile(wallDir+'/pixels.bin',wallPixels);execFileSync('python3',['tools/renderer/record.py','--native','test/fixtures/renderer/walls-angle0','--actual',wallDir,'--build',prefix+'.build.json','--camera',JSON.stringify(scenes[0].camera)],{timeout:30000});
  await writeFile(prefix+'.receipts/walls-angle0.json',JSON.stringify(wall.receipt,null,2)+'\n');
  const wallFrame={status:wall.receipt.status,receiptFile:prefix+'.receipts/walls-angle0.json',name:'walls-angle0',mode:'walls',oneFrame:true,frameSha256:sha(wallPixels),pixelDiffCount:0,gasUsed:Number(BigInt(wall.receipt.gasUsed)),transactionHash:wall.receipt.transactionHash,artifacts:wallDir};
  const calRuntime='6000610123535960005260206000f3',length=(calRuntime.length/2).toString(16).padStart(2,'0'),cal=await deploy('0x60'+length+'600c60003960'+length+'6000f3'+calRuntime),calCall={from,to:cal.receipt.contractAddress,gas};
  const actual=Number(BigInt(await rpc('eth_call',[calCall,'latest']))),trace=await rpc('debug_traceCall',[calCall,'latest',{disableStorage:true,disableStack:false,enableMemory:false}]);assert(!trace.failed);assert.equal(actual,320);assert.equal(traceMemory(trace.structLogs).highWaterBytes,actual);
  await writeFile('web/palette.local.json',JSON.stringify(palette,null,2)+'\n');
  const config={rpcUrl,wsUrl,address,driver:from,deploymentBlock:production.receipt.blockNumber,paletteUrl:'/palette.local.json',paletteKind:'wad',resourceIdentity:identity,rendererKind:'doom-world-view',referenceCase:'full-angle0'};await writeFile(prefix+'.config.json',JSON.stringify(config,null,2)+'\n');
  console.log('Running existing browser gate against genuine production Doom.');const browserStart=performance.now();
  execFileSync(process.execPath,['tools/transport/browser-check.mjs','--existing-config',prefix+'.config.json','--palette',palettePath,'--output-prefix',prefix+'.browser','--timing-script','tools/renderer/browser-timing.js'],{timeout:120000,stdio:['ignore','pipe','inherit'],maxBuffer:8*1024*1024});
  const browser=JSON.parse(await readFile(prefix+'.browser.json','utf8'));assert.equal(browser.kind,'doom-world-view-browser');assert.equal(browser.referenceCase,'full-angle0');assert.equal(browser.receiptPixelsSha256,scenes[0].frameSha256);assert(browser.allCanvasPixelsMatchReceipt&&browser.proof.fallbackVerified);assert.deepEqual(await counters(),{frameId:4,inputSeq:4});
  const browserTimings=browser.timing.requests.filter(r=>r.method==='eth_sendTransaction').map(send=>{const index=browser.proof.frames.findIndex(f=>f.transactionHash===send.transactionHash);assert(index>=0);const canvas=browser.timing.canvas.find(c=>c.frameIndex===index);assert(canvas);const ws=browser.timing.notifications.find(n=>n.transactionHash===send.transactionHash);const receipt=browser.timing.requests.find(r=>r.receipt?.transactionHash===send.transactionHash);assert(receipt);return{transactionHash:send.transactionHash,source:browser.proof.frames[index].source,sendToReceiptMs:receipt.responseAt-send.start,eventDeliveryMs:ws?ws.at-send.start:receipt.responseAt-send.start,deliveryKind:ws?'ws':'receipt-fallback',inputToCanvasMs:canvas.end-send.start,canvasPutImageDataMs:canvas.end-canvas.start};});assert.equal(browserTimings.length,2);for(const t of browserTimings)assert(t.inputToCanvasMs>0&&t.eventDeliveryMs>0);
  for(const [i,t]of browserTimings.entries()){const receipt_=await rpc('eth_getTransactionReceipt',[t.transactionHash]);assert.equal(receipt_.status,'0x1');assert.equal(receipt_.logs.length,1);const f=decodeFrame(receipt_.logs[0]);assert.equal(f.inputSeq,i+3);assert.equal(f.frameId,BigInt(i+3));assert.equal(sha(f.pixels),scenes[0].frameSha256);t.receiptFile=prefix+'.receipts/frame'+(i+3)+'.json';await writeFile(t.receiptFile,JSON.stringify(receipt_,null,2)+'\n');}
  sample();const acceptance={fullCaseCount:8,pixelDiffCount:0,ordinaryResourceDeployment:true,ordinaryDoomDeployment:true,oneFramePerTransaction:true,websocketReceiptPixelsEqual:true,canvasPixelsEqual:true,wallFramePixelDiffCount:0,measuredGasPositive:scenes.every(s=>s.gasUsed>0),measuredMemoryPositive:scenes.every(s=>s.actualMemoryBytes.every(n=>n>0))};
  const report={kind:'doom-world-view-ordinary-e2e',pass:true,acceptance,rendererCommit,compiler,toolchainHashes,client:await rpc('web3_clientVersion'),nodeArgs,sourceHashes:sources,resourceIdentity:identity,blobSha256:sha(blob),directorySha256:sha(directory),chunkCommitment:sha(Buffer.concat(chunks.map(c=>Buffer.from(c.runtimeSha256,'hex')))),deployment:{all1755RuntimeBytesVerified:true,uploadMs,totalChunkGas:chunks.reduce((n,c)=>n+c.gas,0),doom:{...deploySummary(production),runtimeSha256:sha(productionRuntime),runtimeBytes:productionRuntime.length,driver:from,immutableReferences},normalProbe:deploySummary(normal),instrumentedProbe:deploySummary(measured),chunks},instrumentation:telemetry.report,calibration:{actualMsize:actual,derivedHighWater:320,runtime:calRuntime},scenes,productionFrames,rejections,wallFrame,browser:{report:prefix+'.browser.json',screenshot:prefix+'.browser.png',timings:browserTimings,totalCheckMs:performance.now()-browserStart},hostMemory:{peakAnvilRssBytes,peakNodeRssBytes,samplingIntervalMs:1000},notes:['Ordinary CREATE and standard EVM opcodes only; no etch/setCode or custom precompile. Production runtime verified after substituting exactly the artifact-declared immutable driver references.','Every full probe invokes the same DoomRenderer.initialize/render libraries as production; only the probe allows all eight angles. Production Doom emits full-angle0 only.','MSIZE is literal in the separately deployed source-mapped probe: entry, after stored ResourceView copy, after renderer initialization, after full rendering. ABI return encoding follows the last marker. This is not an exact production memory/whole-call peak claim.','Normal/instrumented probe outputs, operation gas, complete transaction gas, and constructor gas agree. Production Doom contains no telemetry logs.','eth_call durations include local RPC/client overhead and are not isolated interpreter CPU time. Send-to-receipt includes execution/mining/RPC. Browser send/event/Canvas timings share its performance.now clock.','Host RSS is sampled, distinct from EVM memory. This finite four-production-frame test does not establish a long-running reset interval.']};
  await writeFile(prefix+'.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({pass:true,acceptance,productionFrames,browserTimings,report:prefix+'.json'},null,2));
  if(keepAlive){console.log(`Verification passed. Anvil remains at ${rpcUrl}. In another terminal run: node tools/transport/serve.mjs
Open http://127.0.0.1:8080 to render more genuine frames. Ctrl-C stops this owned node.`);await new Promise(done=>{const finish=()=>{process.removeListener('SIGINT',finish);process.removeListener('SIGTERM',finish);done();};process.once('SIGINT',finish);process.once('SIGTERM',finish);});}
}catch(error){await writeFile(prefix+'.json',JSON.stringify({kind:'doom-world-view-ordinary-e2e',pass:false,error:String(error),stack:error.stack},null,2)+'\n');throw error;}finally{clearInterval(sampler);subscription?.close();await stop(server);}
