#!/usr/bin/env python3
"""Static original info.c metadata for later sprite setup; no scene or visibility computation."""
import argparse, json, pathlib, re, struct, subprocess, sys, tempfile
sys.path.insert(0,str(pathlib.Path(__file__).resolve().parents[1]))
import reference as ref
ROOT=ref.ROOT; HERE=pathlib.Path(__file__).resolve().parent
FIXTURE=ROOT/'test/fixtures/info'

def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    assert ref.invoke(['git','-C',str(ref.SOURCE),'rev-parse','HEAD']).strip()==ref.UPSTREAM
    ref.invoke(['git','-C',str(ref.SOURCE),'diff','--exit-code','HEAD','--'])
    version=ref.invoke(['clang','--version']).splitlines(); assert version[:2]==[ref.VERSION,'Target: '+ref.TARGET]
    with tempfile.TemporaryDirectory() as temporary:
        temp=pathlib.Path(temporary)
        actions=re.findall(r'void\s+(A_\w+)\s*\(\s*\);',(ref.SOURCE/'info.c').read_text())
        (temp/'actions.c').write_text('#include <stdlib.h>\n'+'\n'.join('void '+name+'(void) { abort(); }' for name in actions))
        outputs=[]
        for opt in ['-O0','-O2']:
            subprocess.run(['clang','-std=c99',opt,'-I'+str(ref.SOURCE),str(HERE/'export.c'),str(ref.SOURCE/'info.c'),str(temp/'actions.c'),'-o',str(temp/'export')],check=True,capture_output=True)
            outputs.append(subprocess.check_output([str(temp/'export')]))
        assert outputs[0]==outputs[1]; raw=outputs[0]
    sprites,states,mobjs=struct.unpack_from('>III',raw); assert len(raw)==12+sprites*4+states*8+mobjs*20
    names=raw[12:12+sprites*4]; state=raw[12+sprites*4:12+sprites*4+states*8]; info=raw[12+sprites*4+states*8:]
    source='''// SPDX-License-Identifier: GPL-2.0-only
// Copyright (C) 1993-1996 by id Software, Inc.
// Generated by tools/reference/info/generate.py from original info.c, never a camera-specific scene.
pragma solidity 0.8.37;

struct InfoData { bytes spriteNames; bytes states; bytes mobjInfo; }
/// @custom:source linuxdoom-1.10/info.c at '''+ref.UPSTREAM+'''
/// @notice Static rendering fields only; no gameplay state actions or thinker implementation.
library Info {
'''+f'    uint32 internal constant NUMSPRITES = {sprites};\n    uint32 internal constant NUMSTATES = {states};\n    uint32 internal constant NUMMOBJTYPES = {mobjs};\n'+'''    function load() internal pure returns (InfoData memory data) {
'''+f'        data.spriteNames=hex"{names.hex()}";\n        data.states=hex"{state.hex()}";\n        data.mobjInfo=hex"{info.hex()}";\n'+'''    }
    function word(bytes memory data,uint256 offset) internal pure returns(uint32 value) {
        require(offset+4<=data.length,"info bounds");
        for(uint256 i;i<4;++i) value=(value<<8)|uint8(data[offset+i]);
    }
}
'''
    source=ref.invoke([str(ROOT/'.toolchain/bin/forge'),'fmt','--root',str(ROOT),'--raw','-'],input=source).encode()
    meta=dict(upstreamCommit=ref.UPSTREAM,compiler=ref.VERSION,target=ref.TARGET,counts=dict(sprites=sprites,states=states,mobjTypes=mobjs),encoding='big-endian u32 counts; sprite names4 bytes; state(sprite,frame)2*u32; mobj(doomednum,spawnstate,flags,radius,height)5*u32, signed values retain two-complement bits',scope='All original static table rendering fields. No WAD, spawn selection, sector assignment, visibility or per-view computation.',sha256=ref.sha(raw),sources={p:ref.sha((ref.SOURCE/p).read_bytes()) for p in ['info.c','info.h','doomdef.h','doomtype.h','p_mobj.h','p_pspr.h','d_think.h','sounds.h']},exporterSha256=ref.sha((HERE/'export.c').read_bytes()),generatorSha256=ref.sha(pathlib.Path(__file__).read_bytes()),soliditySha256=ref.sha(source))
    artifacts={ROOT/'src/doom/info.sol':source,FIXTURE/'tables.bin':raw,FIXTURE/'manifest.json':(json.dumps(meta,indent=2)+'\n').encode()}
    for path,data in artifacts.items():
        if args.check: assert path.read_bytes()==data,'stale '+str(path)
        else: path.parent.mkdir(parents=True,exist_ok=True); path.write_bytes(data)
    print(f'PASS original info.c: {sprites} sprites, {states} states, {mobjs} mobj types; native O0/O2 identical')
if __name__=='__main__': main()
