// SPDX-License-Identifier: GPL-2.0-only
int main(void){int op,n,a[32];while(scanf("%d %d",&op,&n)==2){if(n<0||n>32)exit(3);for(int i=0;i<n;i++)if(scanf("%d",a+i)!=1)exit(3);setup();answer_count=0;
    if(op==0){for(int i=0;i<4;i++){ss[i].floorheight=a[i];ss[i].ceilingheight=a[4+i];ss[i].lightlevel=a[8+i];}for(int i=0;i<3;i++)ls[i].flags=a[12+i];sector_t *s=ss+a[17];out(P_FindLowestFloorSurrounding(s));out(P_FindHighestFloorSurrounding(s));out(P_FindNextHighestFloor(s,a[15]));out(P_FindLowestCeilingSurrounding(s));out(P_FindHighestCeilingSurrounding(s));out(P_FindMinSurroundingLight(s,a[18]));out(sectorid(getNextSector(ls,ss+1)));out(getSide(1,1,1)-sides);out(sectorid(getSector(1,1,1)));out(twoSided(1,1));out(P_FindSectorFromLineTag(ls,a[16]));}
    else if(op==1||op==2){switchlist[0]=10;switchlist[1]=11;switchlist[2]=20;switchlist[3]=21;switchlist[4]=30;switchlist[5]=31;switchlist[6]=-1;numswitches=3;
        if(op==1){sd[0].toptexture=a[0];sd[0].midtexture=a[1];sd[0].bottomtexture=a[2];ls[0].special=a[4];P_ChangeSwitchTexture(ls,a[3]);}
        else {if(a[0]==0)P_StartButton(ls,bottom,30,7);P_StartButton(ls,top,10,35);}
        out(ls[0].special);out(sd[0].toptexture);out(sd[0].midtexture);out(sd[0].bottomtexture);buttons();
    }else if(op==3){leveltime=a[0];levelTimer=a[1];levelTimeCount=a[2];anims[0]=(anim_t){false,4,2,3,8};anims[1]=(anim_t){true,5,4,2,8};lastanim=anims+2;ls[0].special=48;linespeciallist[0]=ls;numlinespecials=1;sd[0].toptexture=11;sd[0].midtexture=21;buttonlist[0]=(button_t){ls,top,10,35,(mobj_t*)&ss[0].soundorg};buttonlist[1]=(button_t){ls,middle,20,1,(mobj_t*)&ss[0].soundorg};P_UpdateSpecials();out(gameaction);out(secretexit);out(levelTimeCount);for(int i=0;i<16;i++)out(textrans[i]);for(int i=0;i<16;i++)out(flattrans[i]);out(sd[0].textureoffset);out(sd[0].toptexture);out(sd[0].midtexture);out(sd[0].bottomtexture);buttons();}
    else if(op==4){resource_mask=a[0];P_InitPicAnims();out(lastanim-anims);for(anim_t *v=anims;v<lastanim;v++){out(v->istexture);out(v->picnum);out(v->basepic);out(v->numpics);out(v->speed);}}
    else if(op==5){gamemode=a[0];P_InitSwitchList();out(numswitches);for(int i=0;i<numswitches*2+1;i++)out(switchlist[i]);}
    else if(op==6){ss[0].special=a[0];player.powers[pw_ironfeet]=a[1];leveltime=a[2];prndindex=a[3];player.health=actors[0].health=a[4];actors[0].z=a[5]?FRACUNIT:0;player.cheats=CF_GODMODE;P_PlayerInSpecialSector(&player);out(actors[0].health);out(player.health);out(player.secretcount);out(ss[0].special);out(player.cheats);out(gameaction);out(secretexit);out(prndindex);out(call_count);for(int i=0;i<call_count;i++)out(calls[i]);}
    else if(op==7){int v=a[0];ss[0].tag=0;ss[1].tag=7;ls[0].tag=v==6?999:7;actors[0].x=10*FRACUNIT;actors[0].y=20*FRACUNIT;actors[0].z=8*FRACUNIT;actors[0].momx=3*FRACUNIT;actors[0].momy=4*FRACUNIT;actors[0].momz=5*FRACUNIT;actors[0].reactiontime=5;actors[0].flags=v==1?MF_MISSILE:0;if(v==4)actors[0].player=NULL;
        for(int i=1;i<4;i++){actors[i].type=MT_TELEPORTMAN;actors[i].subsector=i==2?subs:subs+1;actors[i].x=i*128*FRACUNIT;actors[i].y=32*FRACUNIT;actors[i].angle=i==1?ANG90:ANG180;actors[i].thinker.function.acp1=(actionf_p1)P_MobjThinker;}
        thinker_t *order[]={&actors[0].thinker,&actors[2].thinker,&actors[1].thinker,&actors[3].thinker};thinkercap.next=order[0];thinkercap.prev=order[3];for(int i=0;i<4;i++){order[i]->prev=i?order[i-1]:&thinkercap;order[i]->next=i==3?&thinkercap:order[i+1];}
        if(v==5)actors[1].thinker.function.acv=(actionf_v)-1;if(v==7)actors[1].thinker.function.acv=NULL;teleport_fail=v==3;out(EV_Teleport(ls,v==2?1:0,actors));out(actors[0].x);out(actors[0].y);out(actors[0].z);out(actors[0].angle);out(actors[0].momx);out(actors[0].momy);out(actors[0].momz);out(actors[0].reactiontime);out(player.viewz);out(actor_count);out(call_count);for(int i=0;i<call_count;i++)out(calls[i]);
    }else if(op==8){numsectors=26;numlines=25;for(int i=0;i<26;i++){ss[i].lines=sector_lines[i];ss[i].linecount=0;}for(int i=0;i<25;i++){ls[i].flags=ML_TWOSIDED;ls[i].frontsector=ss;ls[i].backsector=ss+i+1;sector_lines[0][ss[0].linecount++]=ls+i;ss[i+1].floorheight=(100-i)*FRACUNIT;}ss[21].floorheight=FRACUNIT;out(P_FindNextHighestFloor(ss,0));}
    else exit(3);
    word(answer_count);for(int i=0;i<answer_count;i++)word(answer[i]);
}return 0;}
