/* Host I/O and explicit disk parsing only. Rendering/composition bodies are extracted verbatim. */
static uint16_t rd16(byte*p){return p[0]|p[1]<<8;}
static uint32_t rd32(byte*p){return rd16(p)|(uint32_t)rd16(p+2)<<16;}
static void wr32(FILE*f,uint32_t n){for(int i=0;i<4;i++)fputc(n>>(i*8),f);}
static void loadwad(const char*path){FILE*f=fopen(path,"rb");if(!f)abort();fseek(f,0,SEEK_END);long n=ftell(f);rewind(f);wad=malloc(n);if(fread(wad,1,n,f)!=(size_t)n)abort();fclose(f);lumpcount=rd32(wad+4);numlumps=lumpcount;lumpinfo=calloc(lumpcount,sizeof(lumpinfo_t));byte*dir=wad+rd32(wad+8);lumpdata=calloc(lumpcount,sizeof(void*));lumpsize=calloc(lumpcount,4);lumpnames=calloc(lumpcount,8);for(int i=0;i<lumpcount;i++){lumpdata[i]=wad+rd32(dir+i*16);lumpsize[i]=rd32(dir+i*16+4);strncpy(lumpnames[i],(char*)dir+i*16+8,8);memcpy(lumpinfo[i].name,lumpnames[i],8);}}
static void textures_adapter(void){byte*pn=W_CacheLumpNum(W_GetNumForName("PNAMES"),0);int np=rd32(pn);int*lookup=malloc(np*4);for(int i=0;i<np;i++){char name[9]={0};memcpy(name,pn+4+i*8,8);lookup[i]=W_GetNumForName(name);}byte*t1=W_CacheLumpNum(W_GetNumForName("TEXTURE1"),0);int n1=rd32(t1),n2=0;byte*t2=NULL;int k=W_CheckNumForName("TEXTURE2");if(k>=0){t2=W_CacheLumpNum(k,0);n2=rd32(t2);}numtextures=n1+n2;textures=calloc(numtextures,sizeof(void*));texturewidthmask=calloc(numtextures,4);texturecompositesize=calloc(numtextures,4);texturecolumnlump=calloc(numtextures,sizeof(void*));texturecolumnofs=calloc(numtextures,sizeof(void*));texturecomposite=calloc(numtextures,sizeof(void*));for(int i=0;i<numtextures;i++){byte*src=i<n1?t1:t2;int j=i<n1?i:i-n1;byte*def=src+rd32(src+4+j*4);int pc=rd16(def+20);texture_t*t=calloc(1,sizeof(texture_t)+(pc-1)*sizeof(texpatch_t));textures[i]=t;memcpy(t->name,def,8);t->width=rd16(def+12);t->height=rd16(def+14);t->patchcount=pc;for(int p=0;p<pc;p++){byte*x=def+22+p*10;t->patches[p]=(texpatch_t){(int16_t)rd16(x),(int16_t)rd16(x+2),lookup[rd16(x+4)]};}int pow=1;while(pow*2<=t->width)pow*=2;texturewidthmask[i]=pow-1;texturecolumnlump[i]=calloc(t->width,2);texturecolumnofs[i]=calloc(t->width,2);R_GenerateLookup(i);}}
static void emit_resources(const char*path){FILE*f=fopen(path,"wb");if(!f)abort();wr32(f,numtextures);for(int i=0;i<numtextures;i++){texture_t*t=textures[i];wr32(f,t->width);wr32(f,t->height);wr32(f,texturewidthmask[i]);wr32(f,texturecompositesize[i]);for(int x=0;x<t->width;x++){wr32(f,(int32_t)texturecolumnlump[i][x]);wr32(f,texturecolumnofs[i][x]);}if(texturecompositesize[i]){fill=0xa5;R_GenerateComposite(i);byte*a=texturecomposite[i];fill=0x5a;R_GenerateComposite(i);byte*b=texturecomposite[i];for(int x=0;x<texturecompositesize[i];x++){fputc(a[x]==b[x],f);fputc(a[x]==b[x]?a[x]:0,f);}free(a);free(b);texturecomposite[i]=NULL;} }fill=0;R_InitFlats();R_InitSpriteLumps();wr32(f,firstflat);wr32(f,numflats);wr32(f,firstspritelump);wr32(f,numspritelumps);for(int i=0;i<numspritelumps;i++){wr32(f,spritewidth[i]);wr32(f,spriteoffset[i]);wr32(f,spritetopoffset[i]);}fclose(f);}
static void emit_map(const char*path){int base=W_GetNumForName("E1M1");P_LoadVertexes(base+4);P_LoadSectors(base+8);P_LoadSideDefs(base+3);P_LoadLineDefs(base+2);P_LoadSegs(base+5);P_LoadSubsectors(base+6);P_LoadNodes(base+7);FILE*f=fopen(path,"wb");if(!f)abort();wr32(f,numvertexes);for(int i=0;i<numvertexes;i++){wr32(f,vertexes[i].x);wr32(f,vertexes[i].y);}wr32(f,numsectors);for(int i=0;i<numsectors;i++){sector_t*s=sectors+i;wr32(f,s->floorheight);wr32(f,s->ceilingheight);wr32(f,s->floorpic);wr32(f,s->ceilingpic);wr32(f,s->lightlevel);}wr32(f,numsides);for(int i=0;i<numsides;i++){side_t*s=sides+i;wr32(f,s->textureoffset);wr32(f,s->rowoffset);wr32(f,s->toptexture);wr32(f,s->bottomtexture);wr32(f,s->midtexture);wr32(f,s->sector-sectors);}wr32(f,numlines);for(int i=0;i<numlines;i++){line_t*l=lines+i;wr32(f,l->v1-vertexes);wr32(f,l->v2-vertexes);wr32(f,l->dx);wr32(f,l->dy);wr32(f,(uint16_t)l->flags);wr32(f,l->special);wr32(f,l->tag);wr32(f,(int32_t)l->sidenum[0]);wr32(f,(int32_t)l->sidenum[1]);for(int j=0;j<4;j++)wr32(f,l->bbox[j]);wr32(f,l->slopetype);wr32(f,l->frontsector?l->frontsector-sectors:-1);wr32(f,l->backsector?l->backsector-sectors:-1);}wr32(f,numsegs);for(int i=0;i<numsegs;i++){seg_t*s=segs+i;wr32(f,s->v1-vertexes);wr32(f,s->v2-vertexes);wr32(f,s->offset);wr32(f,s->angle);wr32(f,s->sidedef-sides);wr32(f,s->linedef-lines);wr32(f,s->frontsector-sectors);wr32(f,s->backsector?s->backsector-sectors:-1);}wr32(f,numsubsectors);for(int i=0;i<numsubsectors;i++){subsector_t*s=subsectors+i;wr32(f,segs[s->firstline].sidedef->sector-sectors);wr32(f,s->numlines);wr32(f,s->firstline);}wr32(f,numnodes);for(int i=0;i<numnodes;i++){node_t*n=nodes+i;wr32(f,n->x);wr32(f,n->y);wr32(f,n->dx);wr32(f,n->dy);for(int j=0;j<2;j++)for(int k=0;k<4;k++)wr32(f,n->bbox[j][k]);wr32(f,n->children[0]);wr32(f,n->children[1]);}fclose(f);}
static void emit_clip(const char*path){FILE*f=fopen(path,"wb");byte col[]={2,5,0,11,22,33,44,55,0,9,3,0,66,77,88,0,255};for(int origin=-16;origin<=16;origin++)for(int height=1;height<=20;height++){byte cache[20];memset(cache,0xa5,20);R_DrawColumnInCache((column_t*)col,cache,origin,height);fwrite(cache,1,20,f);}fclose(f);}
static void emit_get(const char*path){FILE*f=fopen(path,"wb");fill=0;for(int i=0;i<numtextures;i++){int cols[3]={-1,0,textures[i]->width};for(int j=0;j<3;j++){byte*p=R_GetColumn(i,cols[j]);int lump=texturecolumnlump[i][cols[j]&texturewidthmask[i]];wr32(f,lump);wr32(f,p-(lump>0?lumpdata[lump]:texturecomposite[i]));}}fclose(f);}
static void emit_subsector(const char*path){FILE*f=fopen(path,"wb");unsigned short raw[2];int values[]={0,1,32767,32768,65535};lumpcount=1;lumpdata=malloc(sizeof(void*));lumpsize=malloc(sizeof(int));lumpdata[0]=(byte*)raw;lumpsize[0]=4;for(int i=0;i<5;i++)for(int j=0;j<5;j++){raw[0]=values[i];raw[1]=values[j];P_LoadSubsectors(0);wr32(f,subsectors[0].numlines);wr32(f,subsectors[0].firstline);}fclose(f);}
int main(int argc,char**argv){if(argc==3&&!strcmp(argv[1],"--subsector")){emit_subsector(argv[2]);return 0;}if(argc==3&&!strcmp(argv[1],"--clip")){emit_clip(argv[2]);return 0;}if(argc!=6)return 1;loadwad(argv[1]);textures_adapter();emit_resources(argv[2]);emit_map(argv[3]);emit_clip(argv[4]);emit_get(argv[5]);return 0;}
