#!/usr/bin/env python3
"""Emit immutable native ABI constants; never resource/heap/pixel runtime inputs."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INPUT = ROOT / 'test/fixtures/phase3_zone_lifecycle/layout.json'
OUTPUT = ROOT / 'src/doom/native_zone_layout.sol'


def generate():
    data = INPUT.read_bytes()
    layout = json.loads(data)
    assert layout['upstreamCommit'] == 'a77dfb96cb91780ca334d0d4cfd86957558007e0'
    assert layout['allocationAlignment'] == 8
    lines = [
        '// SPDX-License-Identifier: GPL-2.0-only',
        '// Generated by tools/zone/generate-layout.py from actual pinned C sizeof/offsetof.',
        '// Native allocation layout only; no prepared state, heap bytes or pixels.',
        '// Layout export SHA256: ' + hashlib.sha256(data).hexdigest(),
        'pragma solidity 0.8.37;',
        '',
        'library NativeZoneLayout {',
        '    uint32 internal constant ALLOCATION_ALIGNMENT = 8;',
    ]
    for name, fields in sorted(layout['layout'].items()):
        prefix = name.removesuffix('_t').upper()
        if name == 'primitive':
            for field, value in sorted(fields.items()):
                lines.append(f'    uint32 internal constant PRIMITIVE_{field.upper()} = {value};')
            continue
        lines.append(f'    uint32 internal constant {prefix}_SIZE = {fields["size"]};')
        for field, offset in sorted(fields['offsets'].items()):
            lines.append(f'    uint32 internal constant {prefix}_{field.upper()}_OFFSET = {offset};')
    lines += ['}', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = generate()
    if args.check:
        assert OUTPUT.read_text() == text, 'Native ABI constants are stale'
    else:
        OUTPUT.write_text(text)
    print('PASS generated native ABI constants' + (' check' if args.check else ''))
