#!/usr/bin/env python3
"""Extract pinned C integers; independently compile original tables.c and compare EVERY word."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import struct
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "original/DOOM/linuxdoom-1.10/tables.c"
SOURCE_SHA = "db8759f4311654c63785dcffb8f73a00a61cfe2713e4284c238dea420b6e5f89"
COUNTS = {"finetangent": 4096, "finesine": 10240, "tantoangle": 2049}
HEADER = "// SPDX-License-Identifier: GPL-2.0-only\n// Copyright (C) 1993-1996 by id Software, Inc.\npragma solidity 0.8.37;\n"


def extract():
    source = SOURCE.read_bytes()
    assert hashlib.sha256(source).hexdigest() == SOURCE_SHA, "upstream tables.c changed"
    result = {}
    for name, count in COUNTS.items():
        match = re.search(r"(?:int|angle_t)\s+" + name + r"\[" + str(count) + r"\]\s*=\s*\{([^}]+)\};", source.decode())
        assert match, name
        body = match.group(1)
        assert re.fullmatch(r"[\s,0-9-]+", body), "initializer is not literal integers"
        values = [int(v) for v in body.replace("\n", "").split(",") if v.strip()]
        assert len(values) == count, name
        result[name] = values
    return result


def little(values):
    return b"".join(struct.pack("<I", value & 0xffffffff) for value in values)


def native_compare(tables):
    dumper = '''#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include "tables.h"
_Static_assert(CHAR_BIT == 8 && sizeof(int) == 4 && sizeof(angle_t) == 4, "32-bit table words");
static void word(uint32_t v) { for (unsigned j=0;j<4;j++) putchar((v>>(j*8))&255); }
int main(void) {
 for(unsigned i=0;i<4096;i++) word((uint32_t)finetangent[i]);
 for(unsigned i=0;i<10240;i++) word((uint32_t)finesine[i]);
 for(unsigned i=0;i<2049;i++) word(tantoangle[i]);
 return ferror(stdout) ? 1 : 0;
}
'''
    with tempfile.TemporaryDirectory(prefix="doom-tables-") as temp:
        folder = Path(temp)
        (folder / "dump.c").write_text(dumper)
        subprocess.run(["clang", "-std=c99", "-O2", "-fwrapv", "-fno-strict-aliasing", "-ffp-contract=off", "-fno-fast-math", "-I", str(SOURCE.parent), str(SOURCE), str(folder / "dump.c"), "-o", str(folder / "dump")], check=True)
        actual = subprocess.check_output([str(folder / "dump")])
    expected = b"".join(little(tables[name]) for name in COUNTS)
    assert actual == expected, "original compiled C differs from parsed initializers"
    return len(expected) // 4


def solidity(tables):
    out = HEADER + '''
/// @custom:source linuxdoom-1.10/tables.c, tables.h at a77dfb96cb91780ca334d0d4cfd86957558007e0
/// @dev Generated by tools/tables/generate.py; no host trigonometry. Do not edit.
/// Two-level packed-word switches return scalar values without allocating lookup buffers.
/// Packed constants are big-endian;
/// manifest hashes and Foundry all-index checks use canonical little-endian 32-bit words.
library Tables {
    uint32 internal constant FINEANGLES = 8192;
    uint32 internal constant FINEMASK = 8191;
    uint32 internal constant ANGLETOFINESHIFT = 19;
    uint32 internal constant ANG45 = 0x20000000;
    uint32 internal constant ANG90 = 0x40000000;
    uint32 internal constant ANG180 = 0x80000000;
    uint32 internal constant ANG270 = 0xc0000000;
    uint32 internal constant SLOPERANGE = 2048;
    uint32 internal constant SLOPEBITS = 11;
    uint32 internal constant DBITS = 5;
    error TableIndexOutOfBounds(uint256 index, uint256 length);

    function SlopeDiv(uint32 num, uint32 den) internal pure returns (uint32) {
        if (den < 512) return SLOPERANGE;
        uint32 ans = (num << 3) / (den >> 8);
        return ans <= SLOPERANGE ? ans : SLOPERANGE;
    }

    function finecosine(uint256 index) internal pure returns (int32) {
        if (index >= FINEANGLES) revert TableIndexOutOfBounds(index, FINEANGLES);
        return finesine(index + FINEANGLES / 4);
    }

    function _word(bytes32 group, uint256 index) private pure returns (uint32 value) {
        // Eight original 32-bit words per stack constant. No memory access or allocation.
        assembly ("memory-safe") {
            value := and(shr(sub(224, mul(and(index, 7), 32)), group), 0xffffffff)
        }
    }
'''
    for name, values in tables.items():
        typename = "uint32" if name == "tantoangle" else "int32"
        out += f"\n    function {name}(uint256 index) internal pure returns ({typename}) {{\n"
        out += f"        if (index >= {len(values)}) revert TableIndexOutOfBounds(index, {len(values)});\n"
        out += '        bytes32 group;\n        assembly ("memory-safe") {\n            switch shr(8, index)\n'
        for chunk, start in enumerate(range(0, len(values), 256)):
            out += f'            case {chunk} {{\n                switch and(shr(3, index), 31)\n'
            for group_index, first in enumerate(range(start, min(start + 256, len(values)), 8)):
                blob = b"".join(struct.pack(">I", value & 0xffffffff) for value in values[first:first+8]).ljust(32, b'\0').hex()
                out += f'                case {group_index} {{ group := 0x{blob} }}\n'
            out += '            }\n'
        out += '        }\n'
        out += f"        return {typename}(_word(group, index));\n    }}\n"
    return subprocess.check_output([str(ROOT / ".toolchain/bin/forge"), "fmt", "--raw", "-"], input=(out + "}\n").encode(), cwd=ROOT).decode()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="regenerate committed Solidity and manifest")
    args = parser.parse_args()
    tables = extract()
    count = native_compare(tables)
    all_tables = dict(tables, finecosine=tables["finesine"][2048:10240])
    manifest = {"schemaVersion": 1, "upstreamCommit": "a77dfb96cb91780ca334d0d4cfd86957558007e0", "sourceSha256": SOURCE_SHA, "byteOrder": "little-endian", "tables": [{"name": name, "count": len(values), "wordType": "uint32" if name == "tantoangle" else "int32", "sha256": hashlib.sha256(little(values)).hexdigest()} for name, values in all_tables.items()]}
    artifacts = {ROOT / "src/doom/tables.sol": solidity(tables), ROOT / "tools/tables/manifest.json": json.dumps(manifest, indent=2) + "\n"}
    for path, data in artifacts.items():
        if args.write:
            path.write_text(data)
        else:
            assert path.read_text() == data, f"generated artifact differs: {path}"
    print(f"PASS: {count} original C words equal every extracted initializer; all generated bytes/checksums match")


if __name__ == "__main__":
    main()
