// SPDX-License-Identifier: GPL-2.0-only
// ABI constants generated by pinned cast: sig-event / sig. No scene geometry or rendering here.
export const FRAME_TOPIC = '0x8c71e36358c1759fef7ef5d3abaf6c85f385b13e3579e3d62b00529c4babe922';
export const STEP_SELECTOR = '0x18e65d56';
export function stepData(sequence) {
  if (!Number.isInteger(sequence) || sequence < 1 || sequence > 0xffffffff) throw Error('Invalid input sequence');
  return STEP_SELECTOR + '0'.repeat(64) + sequence.toString(16).padStart(64, '0');
}
export function decodeFrame(log) {
  if (log.topics?.length !== 3 || log.topics[0].toLowerCase() !== FRAME_TOPIC) throw Error('Not a Frame log');
  if (!/^0x(?:[\da-f]{2})+$/i.test(log.data)) throw Error('Malformed log hex');
  const data = log.data.slice(2);
  const word = offset => { if (data.length < (offset + 32) * 2) throw Error('Truncated ABI'); return BigInt('0x' + data.slice(offset * 2, (offset + 32) * 2)); };
  const width = Number(word(0)), height = Number(word(32));
  if (width < 1 || height < 1 || width > 65535 || height > 65535 || word(64) !== 96n) throw Error('Invalid dimensions or ABI offset');
  const length = Number(word(96));
  if (length !== width * height || data.length !== (128 + Math.ceil(length / 32) * 32) * 2) throw Error('Invalid pixel length');
  const frameId = BigInt(log.topics[1]), inputSeq = BigInt(log.topics[2]);
  if (frameId < 1n || frameId > 0xffffffffffffffffn || inputSeq < 1n || inputSeq > 0xffffffffn) throw Error('Invalid counters');
  const pixels = Uint8Array.from(data.slice(256, 256 + length * 2).match(/../g), x => parseInt(x, 16));
  return { frameId, inputSeq: Number(inputSeq), width, height, pixels, log };
}
export function expandPalette(frame, rgb) {
  if (rgb.length !== 768) throw Error('Palette must contain 768 bytes');
  const rgba = new Uint8ClampedArray(frame.pixels.length * 4);
  for (let i = 0; i < frame.pixels.length; i++) {
    const color = frame.pixels[i] * 3;
    rgba.set([rgb[color], rgb[color + 1], rgb[color + 2], 255], i * 4);
  }
  return rgba;
}
export function makeRpc(url) {
  let id = 0;
  return async (method, params = []) => {
    const response = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', id: ++id, method, params }), signal: AbortSignal.timeout(30000) });
    if (!response.ok) throw Error(`RPC HTTP ${response.status}`);
    const result = await response.json();
    if (result.error) throw Error(`${method}: ${JSON.stringify(result.error)}`);
    return result.result;
  };
}
export async function receipt(rpc, hash) {
  const deadline = performance.now() + 30000;
  while (performance.now() < deadline) {
    const result = await rpc('eth_getTransactionReceipt', [hash]);
    if (result) return result;
    await new Promise(resolve => setTimeout(resolve, 20));
  }
  throw Error(`Receipt timeout: ${hash}`);
}
// Deduplicate transaction/log identity, then enforce monotonically increasing frameId.
// Gaps are allowed (show newest available), old arrivals never overwrite newer frames.
export class FrameInbox {
  constructor(onFrame) { this.onFrame = onFrame; this.seen = new Set(); this.latest = 0n; this.duplicates = 0; this.stale = 0; }
  accept(log, source) {
    if (log.removed) throw Error('Removed Frame: local chain changed; reload the session');
    const frame = decodeFrame(log);
    const key = `${log.transactionHash.toLowerCase()}:${BigInt(log.logIndex)}`;
    if (this.seen.has(key)) { this.duplicates++; return false; }
    this.seen.add(key);
    // Bounded recent dedup keys; frame ordering still rejects older entries after eviction.
    if (this.seen.size > 2048) this.seen.delete(this.seen.values().next().value);
    if (frame.frameId <= this.latest) { this.stale++; return false; }
    this.latest = frame.frameId;
    this.onFrame(frame, source);
    return true;
  }
}
export class FrameSubscription {
  constructor(url, address, onLog, onDisconnect = () => {}) {
    this.url = url; this.address = address; this.onLog = onLog; this.onDisconnect = onDisconnect; this.socket = null;
  }
  async connect() {
    this.close();
    const socket = new WebSocket(this.url); this.socket = socket;
    await new Promise((resolve, reject) => {
      const timer = setTimeout(() => { socket.close(); reject(Error('WS subscribe timeout')); }, 10000);
      const fail = () => { clearTimeout(timer); reject(Error('WS disconnected during subscription')); };
      socket.addEventListener('error', fail, { once: true });
      socket.addEventListener('close', fail, { once: true });
      socket.addEventListener('open', () => socket.send(JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'eth_subscribe', params: ['logs', { address: this.address, topics: [FRAME_TOPIC] }] })));
      socket.addEventListener('message', event => {
        try {
          const message = JSON.parse(event.data);
          if (message.id === 1) {
            clearTimeout(timer);
            if (message.error) reject(Error(JSON.stringify(message.error)));
            else { this.subscriptionId = message.result; resolve(); }
          } else if (message.method === 'eth_subscription') this.onLog(message.params.result);
        } catch (error) { this.onDisconnect(error); }
      });
      socket.addEventListener('close', () => { if (this.socket === socket) this.onDisconnect(Error('WS closed; receipt fallback active')); });
    });
  }
  close() { const socket = this.socket; this.socket = null; if (socket) socket.close(); }
}
export async function backfill(rpc, address, fromBlock, inbox) {
  const logs = await rpc('eth_getLogs', [{ address, topics: [FRAME_TOPIC], fromBlock, toBlock: 'latest' }]);
  logs.sort((a, b) => { const x = BigInt(a.blockNumber) - BigInt(b.blockNumber); return Number(x || BigInt(a.logIndex) - BigInt(b.logIndex)); });
  for (const log of logs) inbox.accept(log, 'backfill');
  return logs.length;
}
